AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: >
    battleships-lambda

    Sample SAM Template for battleships-lambda

Globals:
    Function:
        Timeout: 3
        LoggingConfig:
            LogFormat: JSON
Resources:
    CreateGameFunction:
        Type: AWS::Serverless::Function
        Properties:
            CodeUri: create-game/
            Handler: create-game/index.handler
            Runtime: nodejs22.x
            Architectures:
                - x86_64
            Environment:
                Variables:
                    DEPLOY_ENV: local        
            Events:
                CreateGame:
                    Type: Api
                    Properties:
                        Path: /api/create
                        Method: get
        Metadata: # Manage esbuild properties
            BuildMethod: esbuild
            BuildProperties:
                Format: esm
                Minify: true
                Target: es2020
                Sourcemap: true
                OutExtension:
                    - .js=.mjs
                EntryPoints:
                    - index.ts
                External:
                    - "@aws-sdk/client-s3"
