name: Build Lambdas and Deploy

on:
    push:
        branches:
            - main

env:
    AWS_REGION: ap-southeast-1

jobs:
    deploy-lambdas:
        name: Deploy Lambdas
        runs-on: ubuntu-22.04
        environment:
            name: prd-deploy
        permissions:
            id-token: write
            contents: read
        steps:
            - name: Checkout Repository
              uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                  node-version: "22.20.0"
            - name: Install dependencies
              run: |
                  npm ci
                  cd battleships-lambda && npm ci
            - name: build and zip
              env:
                  DEPLOY_ENV: ${{ env.DEPLOY_ENV }}
              run: cd battleships-lambda && npm run build
            - name: Configure AWS Credentials
              uses: aws-actions/configure-aws-credentials@v5.1.0
              with:
                  role-to-assume: ${{ secrets.IAMROLE_GITHUB }} # copy the ARN from AWS
                  role-session-name: GitHub-Action-Role
                  aws-region: ${{ env.AWS_REGION }}

            - name: Deploy Create Game Function
              uses: aws-actions/aws-lambda-deploy@v1.1.0
              with:
                  function-name: battleships-${{ vars.DEPLOY_ENV }}-create-game
                  code-artifacts-dir: battleships-lambda/dist/create-game
                  handler: index.handler
                  runtime: nodejs22.x
                  role: ${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }}
              # FIXME: you need to manually set Lambda Env variables+Cloudfront resource policy+enable function url

            - name: Deploy Join Game Function
              uses: aws-actions/aws-lambda-deploy@v1.1.0
              with:
                  function-name: battleships-${{ vars.DEPLOY_ENV }}-join-game
                  code-artifacts-dir: battleships-lambda/dist/join-game
                  handler: index.handler
                  runtime: nodejs22.x
                  role: ${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }}

            - name: Deploy Get Game Function
              uses: aws-actions/aws-lambda-deploy@v1.1.0
              with:
                  function-name: battleships-${{ vars.DEPLOY_ENV }}-get-game
                  code-artifacts-dir: battleships-lambda/dist/get-game
                  handler: index.handler
                  runtime: nodejs22.x
                  role: ${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }}

            - name: Deploy Submit Action Function
              uses: aws-actions/aws-lambda-deploy@v1.1.0
              with:
                  function-name: battleships-${{ vars.DEPLOY_ENV }}-submit-action
                  code-artifacts-dir: battleships-lambda/dist/submit-action
                  handler: index.handler
                  runtime: nodejs22.x
                  role: ${{ secrets.LAMBDA_EXECUTION_ROLE_ARN }}
            
            - name: Invalidate CloudFront cache
              env:
                CLOUDFRONT_DISTRIBUTION_ID: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
              run: |
                  aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths "/api*"
                
              
